include(CheckCXXCompilerFlag)
if (CMAKE_SYSTEM_NAME MATCHES "CYGWIN")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++0x")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
  message(MESSAGE_FATAL "fisk")
else ()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
endif()

if (CMAKE_SYSTEM_NAME MATCHES "Darwin")
  add_definitions(-D_DARWIN_UNLIMITED_SELECT)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
else ()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpic")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fpic")
endif ()
