include(CheckCXXCompilerFlag)
if (NOT CMAKE_SYSTEM_NAME MATCHES "Darwin")
  check_cxx_compiler_flag("-std=gnu++0x" COMPILER_SUPPORTS_CXX_0X)
  if (COMPILER_SUPPORTS_CXX_0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++0x")
  endif ()
else ()
  add_definitions(-D_DARWIN_UNLIMITED_SELECT)
endif ()
